name: Gemini 3 Property Scout

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # كايخرج يصيد كل ساعة بوحدو
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Elite Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-genai seleniumbase requests # المكتبة الجديدة

      - name: Browser Setup
        run: |
          sbase install chromedriver
          sudo apt install google-chrome-stable

      - name: Launch Mission
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py